--DDL generated by Hibernate on MySql--
CREATE TABLE abridged_cast
(
    pid BIGINT(20) PRIMARY KEY NOT NULL,
    id BIGINT(20),
    name VARCHAR(255),
    fk_abridged BIGINT(20),
    CONSTRAINT FK15aiekedb7itiw0fh92m5twnh FOREIGN KEY (fk_abridged) REFERENCES movies (id)
);
CREATE INDEX FK15aiekedb7itiw0fh92m5twnh ON abridged_cast (fk_abridged);
CREATE TABLE alternate_ids
(
    id BIGINT(20) PRIMARY KEY NOT NULL,
    imdb VARCHAR(255)
);
CREATE TABLE characters
(
    AbridgedCastEntity_pid BIGINT(20) NOT NULL,
    characters VARCHAR(255),
    CONSTRAINT FK4h0sjpd6183evvrmgnas1t9uq FOREIGN KEY (AbridgedCastEntity_pid) REFERENCES abridged_cast (pid)
);
CREATE INDEX FK4h0sjpd6183evvrmgnas1t9uq ON characters (AbridgedCastEntity_pid);
CREATE TABLE hibernate_sequence
(
    next_val BIGINT(20)
);
CREATE TABLE links
(
    id BIGINT(20) PRIMARY KEY NOT NULL,
    alternate VARCHAR(255),
    cast VARCHAR(255),
    review VARCHAR(255),
    self VARCHAR(255),
    similar VARCHAR(255)
);
CREATE TABLE movie_processed_data
(
    id BIGINT(20) PRIMARY KEY NOT NULL,
    duration INT(11),
    posterUrl VARCHAR(255),
    releaseDate DATETIME,
    score INT(11),
    synopsis TEXT,
    thumbUrl VARCHAR(255),
    title VARCHAR(255),
    fk_movie_entity BIGINT(20),
    CONSTRAINT FK34ed0uv17s3wd7t18gema3rga FOREIGN KEY (fk_movie_entity) REFERENCES movies (id)
);
CREATE INDEX FK34ed0uv17s3wd7t18gema3rga ON movie_processed_data (fk_movie_entity);
CREATE TABLE movies
(
    id BIGINT(20) PRIMARY KEY NOT NULL,
    critics_consensus VARCHAR(255),
    mpaa_rating VARCHAR(255),
    runtime INT(11),
    synopsis TEXT,
    title VARCHAR(255),
    year INT(11),
    fk_alternate_ids BIGINT(20),
    fk_links BIGINT(20),
    fk_posters BIGINT(20),
    fk_ratings BIGINT(20),
    fk_release_date BIGINT(20),
    CONSTRAINT FK5oqs4d14o6i00brdchh2memre FOREIGN KEY (fk_alternate_ids) REFERENCES alternate_ids (id),
    CONSTRAINT FK8oqov0kk5qyk105hegh98k073 FOREIGN KEY (fk_release_date) REFERENCES release_dates (id),
    CONSTRAINT FKcdgm2vbnbjasc8ri9teksl4r3 FOREIGN KEY (fk_ratings) REFERENCES ratings (id),
    CONSTRAINT FKeubdxkeju9omnhtfpn6ft0u83 FOREIGN KEY (fk_links) REFERENCES links (id),
    CONSTRAINT FKs3wfmgb902fb5bpfsfdt5nver FOREIGN KEY (fk_posters) REFERENCES posters (id)
);
CREATE INDEX FK5oqs4d14o6i00brdchh2memre ON movies (fk_alternate_ids);
CREATE INDEX FK8oqov0kk5qyk105hegh98k073 ON movies (fk_release_date);
CREATE INDEX FKcdgm2vbnbjasc8ri9teksl4r3 ON movies (fk_ratings);
CREATE INDEX FKeubdxkeju9omnhtfpn6ft0u83 ON movies (fk_links);
CREATE INDEX FKs3wfmgb902fb5bpfsfdt5nver ON movies (fk_posters);
CREATE TABLE posters
(
    id BIGINT(20) PRIMARY KEY NOT NULL,
    detailed VARCHAR(255),
    original VARCHAR(255),
    profile VARCHAR(255),
    thumbnail VARCHAR(255)
);
CREATE TABLE ratings
(
    id BIGINT(20) PRIMARY KEY NOT NULL,
    audience_rating VARCHAR(255),
    audience_score INT(11),
    critics_rating VARCHAR(255),
    critics_score INT(11)
);
CREATE TABLE release_dates
(
    id BIGINT(20) PRIMARY KEY NOT NULL,
    theater VARCHAR(255)
);