package com.vaadin.demo.dashboard.data.db.models;

import com.vaadin.annotations.AutoGenerated;

import javax.persistence.*;

/**
 * Created by Peter on 2016-07-28.
 */
@Entity
@Table(name = "alternate_ids", schema = "vaadin", catalog = "")
public class AlternateIdsEntity {
    private Long id;
    private String imdb;

    public AlternateIdsEntity() { }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique=true, nullable=false)
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Basic
    @Column(name="imdb")
    public String getImdb() {
        return imdb;
    }

    public void setImdb(String imdb) {
        this.imdb = imdb;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        AlternateIdsEntity that = (AlternateIdsEntity) o;

        if (id != that.id) return false;
        return imdb != null ? imdb.equals(that.imdb) : that.imdb == null;

    }

    @Override
    public int hashCode() {
        int result = (int) (id ^ (id >>> 32));
        result = 31 * result + (imdb != null ? imdb.hashCode() : 0);
        return result;
    }
}
