package com.vaadin.demo.dashboard.data.db.models;

import com.vaadin.annotations.AutoGenerated;

import javax.persistence.*;

/**
 * Created by Peter on 2016-07-28.
 */
@Entity
@Table(name = "links", schema = "vaadin", catalog = "")
public class LinksEntity {
    private Long id;
    private String self;
    private String alternate;
    private String cast;
    private String review;
    private String similar;

    public LinksEntity() { }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique=true, nullable=false)
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Basic
    @Column(name = "self")
    public String getSelf() {
        return self;
    }

    public void setSelf(String self) {
        this.self = self;
    }

    @Basic
    @Column(name = "alternate")
    public String getAlternate() {
        return alternate;
    }

    public void setAlternate(String alternate) {
        this.alternate = alternate;
    }

    @Basic
    @Column(name = "cast")
    public String getCast() {
        return cast;
    }

    public void setCast(String cast) {
        this.cast = cast;
    }

    @Basic
    @Column(name = "review")
    public String getReview() {
        return review;
    }

    public void setReview(String review) {
        this.review = review;
    }

    @Basic
    @Column(name = "similar")
    public String getSimilar() {
        return similar;
    }

    public void setSimilar(String similar) {
        this.similar = similar;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        LinksEntity that = (LinksEntity) o;

        if (id != that.id) return false;
        if (self != null ? !self.equals(that.self) : that.self != null) return false;
        if (alternate != null ? !alternate.equals(that.alternate) : that.alternate != null) return false;
        if (cast != null ? !cast.equals(that.cast) : that.cast != null) return false;
        if (review != null ? !review.equals(that.review) : that.review != null) return false;
        return similar != null ? similar.equals(that.similar) : that.similar == null;

    }

    @Override
    public int hashCode() {
        int result = (int) (id ^ (id >>> 32));
        result = 31 * result + (self != null ? self.hashCode() : 0);
        result = 31 * result + (alternate != null ? alternate.hashCode() : 0);
        result = 31 * result + (cast != null ? cast.hashCode() : 0);
        result = 31 * result + (review != null ? review.hashCode() : 0);
        result = 31 * result + (similar != null ? similar.hashCode() : 0);
        return result;
    }
}
