package com.vaadin.demo.dashboard.data.db.models;

import com.vaadin.annotations.AutoGenerated;

import javax.persistence.*;
import java.util.List;

/**
 * Created by Peter on 2016-07-28.
 */
@Entity
@Table(name = "movies", schema = "vaadin", catalog = "")
public class MoviesEntity {

    private Long id;
    private String title;
    private Integer year;
    private String mpaa_rating;
    private Integer runtime;
    private String critics_consensus;
    private String synopsis;
    private ReleaseDatesEntity release_dates;
    private RatingsEntity ratings;
    private PostersEntity posters;
    private AlternateIdsEntity alternate_ids;
    private LinksEntity links;
    private List<AbridgedCastEntity> abridged_cast;

    @Id
    @Column(name = "id")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Basic
    @Column(name = "title")
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Basic
    @Column(name = "year")
    public Integer getYear() {
        return year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    @Basic
    @Column(name = "mpaa_rating")
    public String getMpaa_rating() {
        return mpaa_rating;
    }

    public void setMpaa_rating(String mpaa_rating) {
        this.mpaa_rating = mpaa_rating;
    }

    @Basic
    @Column(name = "runtime")
    public Integer getRuntime() {
        return runtime;
    }

    public void setRuntime(Integer runtime) {
        this.runtime = runtime;
    }

    @Basic
    @Column(name = "critics_consensus")
    public String getCritics_consensus() {
        return critics_consensus;
    }

    public void setCritics_consensus(String critics_consensus) {
        this.critics_consensus = critics_consensus;
    }

    @Basic
    @Column(name = "synopsis", columnDefinition = "TEXT")
    public String getSynopsis() {
        return synopsis;
    }

    public void setSynopsis(String synopsis) {
        this.synopsis = synopsis;
    }

    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "fk_release_date")
    public ReleaseDatesEntity getRelease_dates() {
        return release_dates;
    }

    public void setRelease_dates(ReleaseDatesEntity release_dates) {
        this.release_dates = release_dates;
    }

    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "fk_ratings")
    public RatingsEntity getRatings() {
        return ratings;
    }

    public void setRatings(RatingsEntity ratings) {
        this.ratings = ratings;
    }

    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "fk_posters")
    public PostersEntity getPosters() {
        return posters;
    }

    public void setPosters(PostersEntity posters) {
        this.posters = posters;
    }

    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "fk_alternate_ids")
    public AlternateIdsEntity getAlternate_ids() {
        return alternate_ids;
    }

    public void setAlternate_ids(AlternateIdsEntity alternate_ids) {
        this.alternate_ids = alternate_ids;
    }

    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "fk_links")
    public LinksEntity getLinks() {
        return links;
    }

    public void setLinks(LinksEntity links) {
        this.links = links;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @JoinColumn(name = "fk_abridged")
    public List<AbridgedCastEntity> getAbridged_cast() {
        return abridged_cast;
    }

    public void setAbridged_cast(List<AbridgedCastEntity> abridged_cast) {
        this.abridged_cast = abridged_cast;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        MoviesEntity that = (MoviesEntity) o;

        if (id != that.id) return false;
        if (title != null ? !title.equals(that.title) : that.title != null) return false;
        if (year != null ? !year.equals(that.year) : that.year != null) return false;
        if (mpaa_rating != null ? !mpaa_rating.equals(that.mpaa_rating) : that.mpaa_rating != null) return false;
        if (runtime != null ? !runtime.equals(that.runtime) : that.runtime != null) return false;
        if (critics_consensus != null ? !critics_consensus.equals(that.critics_consensus) : that.critics_consensus != null)
            return false;
        if (synopsis != null ? !synopsis.equals(that.synopsis) : that.synopsis != null) return false;
        if (release_dates != null ? !release_dates.equals(that.release_dates) : that.release_dates != null)
            return false;
        if (ratings != null ? !ratings.equals(that.ratings) : that.ratings != null) return false;
        if (posters != null ? !posters.equals(that.posters) : that.posters != null) return false;
        if (alternate_ids != null ? !alternate_ids.equals(that.alternate_ids) : that.alternate_ids != null)
            return false;
        if (links != null ? !links.equals(that.links) : that.links != null) return false;
        return abridged_cast != null ? abridged_cast.equals(that.abridged_cast) : that.abridged_cast == null;

    }

    @Override
    public int hashCode() {
        int result = (int) (id ^ (id >>> 32));
        result = 31 * result + (title != null ? title.hashCode() : 0);
        result = 31 * result + (year != null ? year.hashCode() : 0);
        result = 31 * result + (mpaa_rating != null ? mpaa_rating.hashCode() : 0);
        result = 31 * result + (runtime != null ? runtime.hashCode() : 0);
        result = 31 * result + (critics_consensus != null ? critics_consensus.hashCode() : 0);
        result = 31 * result + (synopsis != null ? synopsis.hashCode() : 0);
        result = 31 * result + (release_dates != null ? release_dates.hashCode() : 0);
        result = 31 * result + (ratings != null ? ratings.hashCode() : 0);
        result = 31 * result + (posters != null ? posters.hashCode() : 0);
        result = 31 * result + (alternate_ids != null ? alternate_ids.hashCode() : 0);
        result = 31 * result + (links != null ? links.hashCode() : 0);
        result = 31 * result + (abridged_cast != null ? abridged_cast.hashCode() : 0);
        return result;
    }
}
