package com.vaadin.demo.dashboard.data.db.models;

import com.vaadin.annotations.AutoGenerated;

import javax.persistence.*;

/**
 * Created by Peter on 2016-07-28.
 */
@Entity
@Table(name = "ratings", schema = "vaadin", catalog = "")
public class RatingsEntity {
    private Long id;
    private String critics_rating;
    private Integer critics_score;
    private String audience_rating;
    private Integer audience_score;

    public RatingsEntity() { }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique=true, nullable=false)
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Basic
    @Column(name = "critics_rating")
    public String getCritics_rating() {
        return critics_rating;
    }

    public void setCritics_rating(String critics_rating) {
        this.critics_rating = critics_rating;
    }

    @Basic
    @Column(name = "critics_score")
    public Integer getCritics_score() {
        return critics_score;
    }

    public void setCritics_score(Integer critics_score) {
        this.critics_score = critics_score;
    }

    @Basic
    @Column(name = "audience_rating")
    public String getAudience_rating() {
        return audience_rating;
    }

    public void setAudience_rating(String audience_rating) {
        this.audience_rating = audience_rating;
    }

    @Basic
    @Column(name = "audience_score")
    public Integer getAudience_score() {
        return audience_score;
    }

    public void setAudience_score(Integer audience_score) {
        this.audience_score = audience_score;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        RatingsEntity that = (RatingsEntity) o;

        if (id != that.id) return false;
        if (critics_rating != null ? !critics_rating.equals(that.critics_rating) : that.critics_rating != null)
            return false;
        if (critics_score != null ? !critics_score.equals(that.critics_score) : that.critics_score != null)
            return false;
        if (audience_rating != null ? !audience_rating.equals(that.audience_rating) : that.audience_rating != null)
            return false;
        return audience_score != null ? audience_score.equals(that.audience_score) : that.audience_score == null;

    }

    @Override
    public int hashCode() {
        int result = (int) (id ^ (id >>> 32));
        result = 31 * result + (critics_rating != null ? critics_rating.hashCode() : 0);
        result = 31 * result + (critics_score != null ? critics_score.hashCode() : 0);
        result = 31 * result + (audience_rating != null ? audience_rating.hashCode() : 0);
        result = 31 * result + (audience_score != null ? audience_score.hashCode() : 0);
        return result;
    }
}
